### ISSUE TITLE
Add new features: Support —config with Config file

### ISSUE THREAD

**Issue by mqnguyen5** [minhhang107/mh-ssg#10]
Hi Hang, I would like to contribute to the tool by adding support for config files. The details for the feature will be the following:

- [ ] Add new `-c` or `—config` flag thay specifies a path to a JSON config file
- [ ] If the file is missing or can’t be parsed as JSON, exit the program with appropriate error mesage
- [ ] Ignore all other command-line options when accepting `—config`
- [ ] In the config file, ignore any options that the tool doesn’t recognize
- [ ] In the config file, use the default values for unspecified/missing options

Let me know if there is anything I should be aware of when making changes on the code. You can always contact me through Slack if needed.

**Comment by minhhang107** [comment]
Great! Please go ahead
