### ISSUE TITLE
Add Tests for processFolder

### ISSUE THREAD

**Issue by lyu4321** [minhhang107/mh-ssg#14]
Hello, I'd like to create a new test file and add some unit tests for the processFolder function. 

In the unit tests, I will be testing for
- [x] When the input directory has files
- [x] When the input directory does not exist

Please let me know what you think and if I should add any more tests. Thank you!

Edit: Issue updated, will be writing tests for processFolder instead as mentioned in our discussion.

**Comment by minhhang107** [comment]
That sounds great! Pls go ahead
