### ISSUE TITLE
Mistake in the optional feature: Parsing title

### ISSUE THREAD

**Issue by hlavu** [minhhang107/mh-ssg#2]
If there is a title, it will be the first line followed by two blank lines. However, the program will set the whole paragraph as the title if there are no two blank lines. 

orignal txt file
![image](https://user-images.githubusercontent.com/44437742/133519578-5dd7e49c-4830-4b1e-b820-2024caea9b95.png)

generated html file

![image](https://user-images.githubusercontent.com/44437742/133519364-ba5eb07c-7789-4677-bbca-e937f21f871a.png)

**Comment by minhhang107** [comment]
Seems like I forgot to do the check first. Thanks for pointing that out!
