### ISSUE TITLE
Suggestion to use the "chalk" package

### ISSUE THREAD

**Issue by hlavu** [minhhang107/mh-ssg#3]
If you are interested, I suggest using the "chalk" package for log message/error that will make the tool more attractive.
![image](https://user-images.githubusercontent.com/44437742/133529479-4f51183d-9654-42b2-8628-9bcb1e7beaab.png)

**Comment by minhhang107** [comment]
I actually really like your use of chalk in your project and I'm also planning to use it in the next release. Thanks for the suggestion!
