### ISSUE TITLE
Improve your SSG by adding support for markdown files

### ISSUE THREAD

**Issue by tuanthanh2067** [minhhang107/mh-ssg#6]
Hello Hang, I was looking at your project and something just came to my mind that why don't we add a feature that can handle markdown files.

Because of that feature, I need to add some functions to your code

- [ ] Modify  *bin/index.js* so that it will accept both txt files and md files

- [ ] Modify *bin/utils/processFile.js* so that it can handle markdown files

- [ ] Modify docs

Let me know how you think of this idea!

**Comment by minhhang107** [comment]
Sounds great! Please go ahead. Contact me if you need any clarification.
